### ISSUE TITLE
two-letter andrew ID considered invalid

### ISSUE THREAD

**Issue by c-er** [ScottyLabs/print-api#21]
reproduce with
```
$ curl -F "andrew_id=us" -F "file=@test.txt" -F "copies=1" -F "sides=one-sided" https://apis.scottylabs.org/print/v0/printfile
{
  "message": "Please submit a valid Andrew ID.", 
  "status_code": 400
}
```

a two letter andrew ID should pass [the validation code](https://github.com/ScottyLabs/print-api/blob/master/api/printfile.py#L41) so I'm not really sure what's happening.

**Comment by Lexicographical** [comment]
Two-letter andrew IDs should be working now,
